## Numpy array and basics
learn about numpy with chai aur code

In [9]:
import numpy as np
import time

creating array from list

In [5]:
arr_1d=np.array([1,2,3,4,5])
print("1D array:",arr_1d)
arr_2d=np.array([[1,2,3],[3.5,4,5]])
print("2D array:",arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1.  2.  3. ]
 [3.5 4.  5. ]]


## list vs numpy array

In [14]:
py_list = [1,2,3]
print ("Pysthon list multiplication",py_list*2)
np_array =np.array([1,2,3])
print ("Pysthon array multiplication",np_array*2)

start = time.time()
py_list = [i * 2 for  i in range(100000)]
print("\n List operation time:",time.time() -start)

start = time.time()
np_array = np.arange(100000)*2
print("\n Numpy operation time:",time.time() -start)


Pysthon list multiplication [1, 2, 3, 1, 2, 3]
Pysthon array multiplication [2 4 6]

 List operation time: 0.003008127212524414

 Numpy operation time: 0.0010001659393310547


creating array from scratch

In [30]:
zeros= np.zeros((3,4))
print("zeros array: \n",zeros)

ones= np.ones((2,3))
print("ones array: \n",ones)

full= np.full((2,2),7)
print("full array: \n",full)

random =np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0,10,2)
print(" sequence array: \n",sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.76437401 0.77637882 0.51868688]
 [0.21941357 0.91133562 0.61778095]]
 sequence array: 
 [0 2 4 6 8]


Vector , Matrix and tensor


In [45]:
vector = np.array([1,2,3])
print("Vetor: \n",vector)

matrix = np.array([[
    1,2,3],[4,5,6]
])
print ("Matrix: \n", matrix)

tensor = np.array([[[1,2],[4,5]],
[[7,8],[0,1]]])
print ("Tensor:\n", tensor)

Vetor: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [4 5]]

 [[7 8]
  [0 1]]]


Array properties


In [53]:
arr = np.array([[1,2],[4,5]])
print("Shape ",arr.shape)
print("Dimension", arr.ndim)
print("Size",arr.size)
print("Dtype",arr.dtype)


Shape  (2, 2)
Dimension 2
Size 4
Dtype int64


Array Reshaping

In [56]:
arr = np.arange(12)
print("Orignal array: \n ",arr)

reshaped =arr.reshape((3,4))
print ("\n Reshaped array:",reshaped)

flatterned = reshaped.flatten()
print ("\n Flatterned array:",flatterned)

# ravel ( returns view , instead of copy)
raveled = reshaped.ravel()
print ("\n Raveled array:",raveled)

transpose = reshaped.T
print("\n Transpose Array:",transpose)



Orignal array: 
  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flatterned array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose Array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
