## Advance operation with buiness examples 

In [29]:
import numpy as np
import matplotlib.pyplot as plt

In [36]:

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("===== Zomato soles analysis =====")
print("\n Sales Data Shape",sales_data.shape)
print("\n SAmple Data of First three restaurant:\n ",sales_data[0:3])
print("\n SAmple Data of First three restaurant:\n ",sales_data[:,1:])

===== Zomato soles analysis =====

 Sales Data Shape (5, 5)

 SAmple Data of First three restaurant:
  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

 SAmple Data of First three restaurant:
  [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]
