## Numpy Array operations

In [1]:
import numpy as np

In [4]:
arr =np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[2:7])
print("With Step Slicing",arr[1:8:2])
print("Negative Indexing",arr[-3])


Basic Slicing [3 4 5 6 7]
With Step Slicing [2 4 6 8]
Negative Indexing 8


In [3]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Specific element",arr_2d[1,2])
print("Entire row",arr_2d[1])
print("Entire row",arr_2d[:,1])

Specific element 6
Entire row [4 5 6]
Entire row [2 5 8]


Sorting


In [6]:
unsorted=np.array([3,4,1,6,5,2,8,9,7])
print("Sorted array",np.sort(unsorted
))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted  2D array by column",np.sort(arr_2d_unsorted,axis=0))
print("Sorted  2D array by column",np.sort(arr_2d_unsorted,axis=1))

Sorted array [1 2 3 4 5 6 7 8 9]
Sorted  2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted  2D array by column [[1 3]
 [1 2]
 [2 3]]


## Filter

In [8]:
numbers =np.array([1,2,3,4,5,6,7,8,9])
even_number=numbers[numbers%2==0]
print("Even Numbers",even_number)

Even Numbers [2 4 6 8]


Filter with Mask



In [9]:
mask =numbers >5
print("Numbers greater than 5",numbers[mask])

Numbers greater than 5 [6 7 8 9]


## Fancy Indexing vs np.where()


In [12]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print("NP where", numbers[where_result])


[1 3 5]
NP where [6 7 8 9]


In [30]:
condition_array=np.where(numbers>5,numbers*1,numbers)
print(condition_array)

[1 2 3 4 5 6 7 8 9]


## adding and removing data


In [32]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# combined = arr1 + arr2
combined = np.concatenate((arr1 , arr2))
print("Addition of two array",combined)

Addition of two array [1 2 3 4 5 6]


## array compativilty


In [34]:
a= np.array([1,2,3])
b= np.array([4,5,6])
c= np.array([7,8,9])

print("Compatiblity Shapes",a.shape == b.shape)

Compatiblity Shapes True


In [5]:
original = np.array([[1,2],[3,4]])
new_row= np.array([5,6])

with_new_row = np.vstack((original,new_row))

print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_column = np.hstack((original,new_col))
print("With new column",with_new_column)



[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [7]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion",deleted)

Array after deletion [1 2 4 5]
